Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2021-11, with the labels that each got.

#1382 Expand certain FAWE limits to use Long instead of Integer.
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Labels: hacktoberfest-accepted

#1430 upstream: Update upstream
  worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
  worldedit-core/src/main/java/com/sk89q/worldedit/scripting/MinecraftHidingClassShutter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/scripting/RhinoCraftScriptEngine.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/TargetBlock.java
Labels: upstream

#1439 Update paperlib
  gradle/libs.versions.toml
Labels: Renovate
