Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-02, with the labels that each got.

#1607 Fix: Add coordinates to tile-entity nbt component for undo
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java
Labels: Bugfix

#1608 Fix: Set size of MappedByteBuffer accordingly if no file system entry is present
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
Labels: Bugfix

#1616 Fix surfacespline not working below Y 0
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/SurfaceSpline.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/SchemGen.java
Labels: Bugfix

#1618 Fix angle mask not working below Y 0
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ExtentHeightCacher.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AngleMask.java
Labels: Bugfix

#1624 Fix clipboards to allow proper heights by allowing extended CuboidRegion heights
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/MinecraftVersion.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitServerInterface.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/BukkitImplLoader.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/SimpleClipboard.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/Clipboard.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
Labels: Bugfix

#1623 Load legacy config file before firing PlatformsRegisteredEvent
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
Labels: Bugfix

#1620 Fix //snapshot in 1.18 and re-implement biome/entity restoration
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightFaweAdapter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultItemParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/AnvilChunk15.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/AnvilChunk17.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/AnvilChunk18.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/PackedIntArrayReader.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/ChunkStoreHelper.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/TrueZipMcRegionChunkStore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/ZippedMcRegionChunkStore.java
Labels: Bugfix

#1617 Don't allow heightmap-based brushes to edit the entire world "depth"
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/HeightMap.java
Labels: Bugfix

#1631 Bump `actions/setup-java` to 3.0.0
  .github/workflows/build.yml
Labels: Renovate

#1632 Fix 1.17 snapshot restoration
  worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/AnvilChunk17.java
Labels: Bugfix

#1629 Remove stub server test class
  worldedit-bukkit/src/test/java/com/fastasyncworldedit/util/StubServer.java
  worldedit-bukkit/src/test/java/com/sk89q/worldedit/bukkit/BukkitWorldTest.java
Labels: tests
