Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-09, with the labels that each got.

#1929 Upload files to curseforge on release
  .github/workflows/upload-release-assets.yml
Labels: chore

#1884 feature: support paper chunk system
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
Labels: Feature

#1947 Retrieve the latest asset release version automatically
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
Labels: Feature

#1944 Fix #saturate-Pattern
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SaturatePattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
Labels: Bugfix
