Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-05, with the labels that each got.

#1712 Implement getNameUnsafe method to allow an unloaded world's name to be accessed
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/WorldUnloadedException.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
  worldedit-cli/src/main/java/com/sk89q/worldedit/cli/schematic/ClipboardWorld.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/NullWorld.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/World.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Bugfix

#1731 Don't initialise a DiskOptimisedClipboard before checking for an existing one in the LocalSession when using loadClipboardFromDisk
  worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
Labels: Bugfix, Ready for merge

#1732 Check cached bukkit player is the same as the current player online
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditListener.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
Labels: Bugfix

#1737 Cherry pick upstream commits to fix SideEffectSet
  worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/SideEffectConverter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/world/SideEffectExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/wna/WorldNativeAccess.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/SideEffect.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/SideEffectSet.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/formatting/component/SideEffectBox.java
Labels: Bugfix, Ready for merge

#1713 Allow use of BlockVectorSet for large //line selections instead of LocalBlockVectorSet
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BufferedPattern2DParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BufferedPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/CachedMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/BufferedPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/BufferedPattern2D.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/BlockVector3Set.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/input/ParserContext.java
Labels: Bugfix, Ready for merge

#1742 Respect clipboard settings (disk vs memory) when loading a schematic
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardReader.java
Labels: Bugfix, Ready for merge

#1746 Ignore .DS_Store files
  .gitignore
Labels: skip-changelog

#1744 Don't error when loading a schematic fails
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
Labels: Bugfix, Ready for merge

#1750 Add jenkins to downloads list
  README.adoc
Labels: chore

#1754 Attach assets to GH releases
  .github/workflows/upload-release-assets.yml
Labels: Feature, chore

#1756 Update PaperMC repository URL
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_18/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_18_2/build.gradle.kts
  worldedit-bukkit/build.gradle.kts
Labels: chore

#1763 feat: Update Readme SVG
  .idea/icon.svg
  README.adoc
  fawe-logo.png
Labels: skip-changelog
