Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-10, with the labels that each got.

#1968 Release to Modrinth
  .github/workflows/build.yml
  worldedit-bukkit/build.gradle.kts
Labels: hacktoberfest-accepted, Feature

#1948 Fix region restrictions with methods non-overriden
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/FaweRegionExtent.java
Labels: Bugfix

#1973 chore: Re-enable CodeQL
  .github/workflows/codeql.yml
Labels: chore

#1969 Don't error when NPC-annotated "entity" leaves the server
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/BukkitPermissionAttachmentManager.java
Labels: Bugfix

#1980 chore: Announce releases on discord
  .github/workflows/announce-release-on-discord.yml
Labels: chore

#1979 Rewrite README
  .gitignore
  README.adoc
  README.md
  worldedit-bukkit/build.gradle.kts
Labels: chore

#1977 fix: Add items to a player's inventory on the main thread
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/image/BukkitImageViewer.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayerBlockBag.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
Labels: Bugfix

#1982 Fix mappings issue with biome-based regen on 1.18.2
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java
Labels: Bugfix

#1978 fix: Do not cast y to byte in history database
  worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java
Labels: Bugfix

#1976 feat: Reduce any spam caused by exceptions thrown when writing history
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/exception/FaweException.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/exception/FaweSmallEditUnsupportedException.java
Labels: Feature

#1975 fix: Add blocked blocks to the correct set
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/DisallowedBlocksExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
Labels: Bugfix

#1992 fix: bring default min/max y in line with upstream in AbstractRegion
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/AbstractRegion.java
Labels: Bugfix

#1991 fix: move main-thread call to be implementation from WorldWrapper
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java
Labels: Bugfix
