Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-07, with the labels that each got.

#1867 Getting correct String from CompoundTag
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/MutableEntityChange.java
Labels: Bugfix, Ready for merge

#1866 Correct return type for CuboidRegion#getFaces() upstream compatibility
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
Labels: Bugfix, Ready for merge

#1881 fix: use servers removeGameEventListener instead of reimpl
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
Labels: Bugfix

#1885 chore: Reword light command messages
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: chore

#1887 feat: Add support for 1.19.1
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R1/PaperweightAdapter.java
Labels: Major feature
