Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-08, with the labels that each got.

#1889 chore: Use 1.19.1 asset URL
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
Labels: chore

#1888 Improve ``MainUtil#copyFile``
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
Labels: chore

#1898 Add 1.19.2
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R1/PaperweightAdapter.java
Labels: Major feature

#1901 build: Update paperweight
  worldedit-bukkit/adapters/adapter-1_18_2/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19/build.gradle.kts
Labels: Renovate

#1900 chore: Update assets to 1.19.2
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
Labels: chore

#1908 fix: upstream missing `Region#getBoundingBox()`
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Labels: Bugfix

#1911 fix: Lazy fix macro stacktrace
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
Labels: Bugfix

#1922 fix: avoid recursive LegacyMapper initialization
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
Labels: Bugfix

#1921 fix: use proper level data for regen
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/regen/PaperweightRegen.java
Labels: Bugfix
