Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-04, with the labels that each got.

#1677 Simplify internal id lookup logic for biomes
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java
Labels: Ready for Review, Bugfix

#1684 refactor: removed unused variable
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
Labels: Ready for Review, chore

#1693 Fix memory leak by Citizen NPCs
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/BukkitPermissionAttachmentManager.java
Labels: Ready for Review, Bugfix

#1697 Use correct class to look up lock field in 1.17
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
Labels: Bugfix

#1694 Fix Invalid pattern replacement / block category mask
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java
Labels: Ready for Review, Bugfix

#1706 Fix NSME error on Spigot 1.16.5 when using brushes
  worldedit-bukkit/adapters/adapter-legacy/src/main/resources/worldedit-adapters.jar
Labels: Bugfix

#1708 Emphasize project icon in idea selection
  .gitignore
  .idea/icon.svg
Labels: chore

#1703 Show # of affected blocks in //set command
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#1710 Set empty block count when using fastmode on 1.17
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-legacy/src/main/resources/worldedit-adapters.jar
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java
Labels: Bugfix

#1718 Fix some horrendous code where methods supposed to return a boolean only ever return true
  worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/LocationMaskedPlayerWrapper.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/NavigationCommands.java
Labels: Major bug fix
