Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-06, with the labels that each got.

#1743 Implement biomes to filter blocks and use in Clipboard pasting
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/LinearClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/AbstractFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/AbstractSingleFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ArrayFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ExtentFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/FilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/DelegateBlockVector3.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/BlockArrayClipboard.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/Clipboard.java
  worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3.java
Labels: Bugfix

#1715 Some fixes and improvements to internal queuing
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/concurrent/ReentrantWrappedStampedLock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharGetBlocks.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
Labels: Major bug fix, Bugfix

#1711 Avoid int overflow when using fillr in negative coords
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Labels: Bugfix

#1770 Add block break effect to area pickaxe
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/AreaPickaxe.java
Labels: Enhancement, Ready for merge

#1745 Allow NBT stored in DiskOptimizedClipboards to be written to disk as a compressed byte array at the end of the file
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/exception/FaweClipboardVersionMismatchException.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/io/ByteBufferInputStream.java
  worldedit-core/src/main/java/com/sk89q/jnbt/NBTInputStream.java
  worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature, Ready for merge

#1778 build: Switch to bom
  buildSrc/src/main/kotlin/AdapterConfig.kt
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  gradle/libs.versions.toml
  worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_18/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_18_2/build.gradle.kts
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweQueueCoordinator.java
  worldedit-cli/build.gradle.kts
  worldedit-core/build.gradle.kts
Labels: Enhancement

#1779 chore: Drop WEManager#cancelEditSafe() logger
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java
Labels: Ready for merge, chore

#1782 Apply DelegateSemaphore fixes to 1.19
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/DelegateSemaphore.java
Labels: Bugfix

#1790 Implement limits to image size and load times
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature, Ready for merge

#1788 Only synchronise tree generation at the very lowest level
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-legacy/src/main/resources/worldedit-adapters.jar
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweAPI.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java
Labels: Bugfix, Ready for merge

#1796 Command block messages should be sent on the main thread as it causes a block update
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockCommandSender.java
Labels: Bugfix

#1789 Only implement cache to MaskingExtent when off main thread
  worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweCache.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java
Labels: Bugfix

#1751 Don't apply offset to SimpleClipboard
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/SimpleClipboard.java
Labels: Bugfix, Ready for merge

#1801 fix: Suppress Tuinity light exception on 1.16
  worldedit-bukkit/adapters/adapter-legacy/src/main/resources/worldedit-adapters.jar
Labels: Bugfix

#1804 fix: Run GriefPrevention region check in sync
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefPreventionFeature.java
Labels: Bugfix, Ready for merge

#1800 Only create entities during a restore if they are contained by the region and the editsession's mask
  worldedit-core/src/main/java/com/sk89q/worldedit/world/snapshot/SnapshotRestore.java
Labels: Bugfix, Ready for merge

#1798 Use the correct CuboidRegion constructor to prevent clipboard height being limited when loading schematics
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardReader.java
Labels: Bugfix, Ready for merge

#1811 Prevent unhinged tree generation by doing a sanity check on the block below/block of the tree placement
  worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
Labels: Bugfix, Ready for merge

#1809 Processor should be added to queue, not extent
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
Labels: Bugfix, Ready for merge

#1806 The extent minY check in clipboard paste is un-needed as it is handled gracefully by FAWE
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/Clipboard.java
Labels: Bugfix, Ready for merge

#1787 Fixes to BlockMask and "char" masks
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/StringMan.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskIntersection.java
Labels: Bugfix, Ready for merge

#1824 docs: Publish javadocs to GH pages
  .github/workflows/build.yml
  .github/workflows/codeql.yml.disabled
  README.adoc
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
Labels: documentation

#1825 Don't do the unbelievable bad use of a MutableBlockVector2 in the creation of a set
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/MemBlockSet.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
Labels: Bugfix

#1815 Fix saving entities in DiskOptimizedClipboard when no tiles are present
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
Labels: Bugfix

#1817 Allow editing solely of tiles/entities/heightmaps
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java
Labels: Bugfix

#1818 Don't limit split size for extra block data (signs, spawner, etc.)
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
Labels: Bugfix

#1816 Fix #fullcopy -r
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RandomFullClipboardPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java
Labels: Bugfix

#1810 Actually apply source mask when using //paste -m <mask>
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
Labels: Bugfix

#1819 Implement generation of biome decorations to //regen <biome> and add option for a random seed to be used
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/regen/PaperweightRegen.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
Labels: Feature

#1827 Support using //distr on console properly
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java
Labels: Bugfix

#1835 chore: Add runServer task
  build.gradle.kts
Labels: skip-changelog

#1830 Set the correct delegate to the ChunkHolder when using get or set in NULL delegate
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
Labels: Bugfix, Ready for merge

#1831 Account for use of MutableBlockVector3 in Spline Brush
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/SplineBrush.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/visitor/DFSRecursiveVisitor.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/visitor/DFSVisitor.java
Labels: Bugfix, Ready for merge

#1812 Re-implement full Entity support in history, entity removal, entity creation, etc.
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-legacy/src/main/resources/fastasyncworldedit-adapters.jar
  worldedit-cli/src/main/java/com/sk89q/worldedit/cli/schematic/ClipboardWorld.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/FaweRegionExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/HistoryExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/NullExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ProcessedWEExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/StripNBTExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/CPUOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/LinearClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/MemoryOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/ReadOnlyClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/transform/MultiTransform.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/transform/ScaleTransform.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/transform/SelectTransform.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/MutableEntityChange.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java
  worldedit-core/src/main/java/com/sk89q/jnbt/CompoundTag.java
  worldedit-core/src/main/java/com/sk89q/jnbt/NBTUtils.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/ChangeSetExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/NullExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/TracingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/BlockArrayClipboard.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/world/WatchdogTickingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/entity/ExtentEntityCopy.java
  worldedit-core/src/main/java/com/sk89q/worldedit/session/request/RequestExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/NullWorld.java
Labels: Major feature, Ready for merge

#1829 Use Material rather than legacy int/data when specifying block break effect type
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/AbstractWorld.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/World.java
Labels: Bugfix

#1832 Implement a "sensitivity" setting, a mask, and an option to only distinguish air vs blocks to blendball
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/BlendBall.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/CachedMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
Labels: Feature

#1833 Re-implement incremental schematic names in a folder
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
Labels: Feature

#1838 Assume a file not being in a subdirectory of root means a symlink is used
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
Labels: Feature

#1840 Actually implement ChunkHolder/ChunkSet pools
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
Labels: Bugfix, Ready for merge

#1821 Fix walls command on 1D/2D selection
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
Labels: Bugfix
