Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2022-01, with the labels that each got.

#1507 Add worldedit.schematic.list.other permission and functionality
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/StringMan.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
Labels: Enhancement

#1520 refactor: Tackle a few Semgrep and ErrorProne violations
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_18_R1/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/DoNotMiniseThese.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/TypeDescription.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/jnbt/NBTException.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/jnbt/streamer/ValueReader.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/AverageHeightMapFilter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/registry/state/PropertyKeySet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ColorUtil.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/StringMan.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/IAdaptedMap.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/YieldIterable.java
  worldedit-core/src/main/java/com/sk89q/util/ReflectionUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/Link.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/TargetBlock.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/logging/DynamicStreamHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
Labels: skip-changelog

#1526 ci: Cleanup maven repositories
  buildSrc/src/main/kotlin/AdapterConfig.kt
  buildSrc/src/main/kotlin/CommonConfig.kt
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_18/build.gradle.kts
  worldedit-bukkit/build.gradle.kts
Labels: skip-changelog

#1533 Put Fawe version information at debugpaste top
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/WorldEditCommands.java
Labels: chore

#1522 Heightmaps used for brushes etc. should be normalised to zero.
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/HeightBrush.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/ArrayHeightMap.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/FlatScalableHeightMap.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/HeightMap.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/ScalableHeightMap.java
Labels: Ready for Review, Bugfix

#1553 fix: Unify superpickaxe behavior
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
Labels: Bugfix

#1546 Fix: GriefDefender filter
  gradle/libs.versions.toml
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefDefenderFeature.java
Labels: Bugfix

#1557 Deduplicate error messages
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ChunkCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
Labels: Bugfix

#1583 fix: `/fawe debugpaste` not working on 1.17 and lower due GSON incompatibility with Paster library
  gradle/libs.versions.toml
  worldedit-bukkit/build.gradle.kts
Labels: Bugfix

#1551 Only call `org.bukkit.World` height methods if they're present (1.17+)
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefPreventionFeature.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
Labels: Bugfix
