Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-02, with the labels that each got.

#2081 Add metrics for Residence
  gradle/libs.versions.toml
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/build.gradle.kts
Labels: skip-changelog

#2086 Use Pattern Matching for instanceof in PropertyKeySet
  worldedit-core/src/main/java/com/fastasyncworldedit/core/registry/state/PropertyKeySet.java
Labels: chore

#2083 Remove PlayerMoveEvent listener and deprecate MovableTool
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/listener/BrushListener.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/MovableTool.java
Labels: chore

#2098 Move Jenkinsfile from ps-v7 to general branch
  Jenkinsfile
Labels: skip-changelog

#2119 Fix reading block states in no redo mode
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
Labels: Bugfix
