Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-05, with the labels that each got.

#2196 Actually delegate in AbstractDelegateExtent
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
  worldedit-core/src/test/java/com/fastasyncworldedit/ArchitecturalTest.java
Labels: Bugfix

#2193 Fixes command context for bukkit console command sender
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/ConfirmHandler.java
Labels: Bugfix

#2220 Properly scale the random in SimpleRandomCollection
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/SimpleRandomCollection.java
Labels: Bugfix

#2221 Simplify Java location in Jenkinsfile
  Jenkinsfile
Labels: skip-changelog

#2229 Revert "Actually delegate in AbstractDelegateExtent"
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
  worldedit-core/src/test/java/com/fastasyncworldedit/ArchitecturalTest.java
Labels: Bugfix

#2211 Fix reading of tile entities with "id" instead of "Id" tag
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicReader.java
Labels: Bugfix, Feature

#2230 fix: correct issues with processor scopes
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/DisallowedBlocksExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/FaweRegionExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/MultiBatchProcessor.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/ProcessorScope.java
Labels: Bugfix

#2231 fix: correctly in initialise unlimited limit
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
Labels: Bugfix

#2234 chore: remove firework-chunk-loading prevention and default tick limiter to false
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/listener/ChunkListener.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
Labels: chore

#2233 fix: more intuitive limit permissions
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
Labels: Bugfix

#2232 fix: correctly handle creation of extents in EditSessionBuilder
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
Labels: Bugfix

#2236 fix: create single threaded executor for use with non-concurrent generators
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
Labels: Bugfix

#2237 fix: fix universal disallowed blocks logic in limit and EditSession compilation
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
Labels: Bugfix

#2239 feat: allow captions in SuggestInputParseException
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/SuggestInputParseException.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RichPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
Labels: Feature

#2238 fix: only send invalid region messages with debug true
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java
Labels: Bugfix

#2235 feat: make more commands unqueued
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BiomeCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ChunkCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GeneralCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/NavigationCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SnapshotCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SnapshotUtilCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
Labels: Feature

#2244 feat: add -r (random rotate) flag to schem load and clipboard brush
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/ClipboardBrush.java
Labels: Feature

#2248 refactor: switch to EnumSet for heightmaps to improve performance
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java
Labels: Performance, chore

#2243 feat: configurable image hosts
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/image/ImageUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java
Labels: Feature
