Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-03, with the labels that each got.

#2123 Fix FAWE using exclusive build height from PlotSquared
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
Labels: Bugfix

#2092 Fix off by one error for negative coordinates when using -r with //deform
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Labels: Bugfix

#2127 Use unsynchronized buffered OutputStream for history
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/io/FaweOutputStream.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
Labels: Enhancement

#2134 Misc. dependency update to align with libs.versions.toml
  buildSrc/src/main/kotlin/CommonConfig.kt
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
Labels: Renovate

#2136 Fetch userdev plugin from plugin portal
  buildSrc/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_18_2/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19_3/build.gradle.kts
Labels: chore

#2150 Bump run paper to 1.19.3 and replace path with better solution
  build.gradle.kts
Labels: Feature, chore

#2153 fix: clear above and below plot gen heights if build heights are larger
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweDelegateRegionManager.java
Labels: Bugfix

#2146 Add nether tress into floating tree remover
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/FloatingTreeRemover.java
Labels: Feature

#2162 feat: improvements to clipboard on disk
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
Labels: Feature

#2160 fix: add null-check for brush in traceMask
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Bugfix
