Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-12, with the labels that each got.

#2510 fix: set biome biome on clear
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweDelegateRegionManager.java
Labels: Bugfix

#2420 Unify the limit permission
  worldedit-bukkit/src/main/resources/plugin.yml
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
Labels: chore

#2500 fix: add chunk loc to tile entity location when trimming
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/HeightBoundExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunk.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Labels: Bugfix

#2524 chore: add a more informative error when parsing block properties
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: chore

#2526 feat: add config option for if the DOC should lock the file channel
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
Labels: Feature

#2365 fix: correct the delegated methods in AbstractDelegateExtent
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
Labels: Bugfix
