Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-07, with the labels that each got.

#2307 refactor: some changes that may help #2289
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/session/SessionManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/session/storage/JsonFileSessionStore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemType.java
Labels: chore

#2336 fix: ignore clipboard origin when pasting to match P2 behaviour
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweDelegateRegionManager.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweDelegateSchematicHandler.java
Labels: Bugfix

#2333 fix: correctly invalidate mask after a plot is merged
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
Labels: Bugfix

#2322 feat: allow bracketless '%' pattern definition
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RichPatternParser.java
Labels: Feature

#2323 fix: ensure chunk is loaded when getting entities
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java
Labels: Bugfix

#2338 Deprecate support for 1.16.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  build.gradle.kts
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/MinecraftVersion.java
Labels: Developer

#2331 refactor: use HttpClient for update check
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java
Labels: chore

#2340 chore: deprecate some methods that ought to be removed
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TaskManager.java
Labels: chore

#2347 fix: fix command brush
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/CommandBrush.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ScatterCommand.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
Labels: Bugfix

#2341 feat: provide some information upon OverlappingFileLockException
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
Labels: Feature

#2351 fix: fix adding/getting masks to/from MaskExtent when it is a processor
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Labels: Bugfix

#2342 feat: synchronise disk clipboard loading and deletion to clipboardLock
  worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
Labels: Feature

#2339 feat: re-submit chunk load request after 10s after checking world is loaded
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java
Labels: Feature

#2363 fix: regions not trimming Y correctly when restricted
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
Labels: Bugfix

#2362 fix: correct NBT for spawners
  worldedit-core/src/legacy/java/com/sk89q/worldedit/blocks/MobSpawnerBlock.java
Labels: Bugfix

#2361 fix: make IdMask thread-safe
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/IdMask.java
Labels: Bugfix

#2358 fix: do not retain clipboards that completed exceptionally
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
Labels: Bugfix

#2353 fix: do not clash ChunkHolder recycling with processors that extend outside the chunk
  worldedit-core/src/main/java/com/fastasyncworldedit/core/concurrent/ReentrantWrappedStampedLock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
Labels: Bugfix

#2346 feat: implement a new "type swap" pattern
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/TypeSwapPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/TypeSwapPattern.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java
Labels: Feature

#2334 Implement async notify queue that submits to a KeyQueuedExecutorService
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/QueueHandler.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/AsyncNotifyKeyedQueue.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/AsyncNotifyQueue.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractNonPlayerActor.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlayerActor.java
Labels: Feature

#2075 Update PlotSquared integration to v7
  .github/renovate.json
  buildSrc/src/main/kotlin/AdapterConfig.kt
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  gradle/libs.versions.toml
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweDelegateRegionManager.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweTrim.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSetBiome.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
  worldedit-bukkit/src/test/java/com/sk89q/wepif/TestOfflinePermissible.java
  worldedit-core/build.gradle.kts
Labels: Major feature

#2369 fix: don't warn on release build
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java
Labels: Bugfix

#2368 fix: disallowed regions can be length 0
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
Labels: Bugfix
