Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-11, with the labels that each got.

#2475 Support -n (select only) in //place
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
Labels: hacktoberfest-accepted, Bugfix

#2489 Only unlock if previously locked
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
Labels: Bugfix

#2482 Reuse generateTree code across versions
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java
Labels: chore

#2367 fix: fixed history rollback
  worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/RollbackOptimizedHistory.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Major bug fix, Bugfix

#2497 Drop support for 1.16.5 and 1.17
  settings.gradle.kts
  worldedit-bukkit/adapters/adapter-legacy/build.gradle.kts
  worldedit-bukkit/adapters/adapter-legacy/src/main/resources/fastasyncworldedit-adapters.jar
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/MinecraftVersion.java
Labels: Breaking changes
