Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-04, with the labels that each got.

#2167 Update renovate.json
  renovate.json
Labels: skip-changelog

#2172 Improve testability by adding more versions of runPaper to the build scripts
  build.gradle.kts
Labels: skip-changelog

#2166 Update paperweight version for 1.19.4
  worldedit-bukkit/adapters/adapter-1_19_4/build.gradle.kts
Labels: chore

#2174 Fix Misaligned SVG In IJ project view
  .idea/icon.svg
Labels: chore

#2157 fix: invalidate cached FaweMask when a plot is unlinked
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
Labels: Bugfix

#2161 fix: Ensure BaseBlock is not returned when a BlockState is wanted in BlockTransformExtent (#2161
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/transform/BlockTransformExtent.java
Labels: Bugfix

#2179 Address incompatibilities after CraftChunk changes in spigot
  worldedit-bukkit/adapters/adapter-1_19_4/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/regen/PaperweightRegen.java
Labels: Bugfix

#2163 chore: add chunk tickets to all chunks accessed
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
Labels: Feature, chore

#2186 Add an explanation to Disallowed-Blocks Comment
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
Labels: Bugfix, skip-changelog

#2185 Ensure regen step not running on the main thread
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
Labels: Bugfix
