Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-01, with the labels that each got.

#2062 Remove usages of JoinedCharSequence
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/JoinedCharSequence.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemTypes.java
Labels: chore

#2070 Terminate process if `.git` folder does not exist
  build.gradle.kts
Labels: skip-changelog

#2071 Split workflows
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
Labels: skip-changelog

#2068 fix: don't quash a cancellation FaweException in LimitExtent
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
Labels: Bugfix

#2060 Fix: remove unnecessary bypass permission
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
Labels: Bugfix

#2012 fix regex and remove forbidden windows characters
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
Labels: Bugfix, chore

#2079 Linear Patterns require flooring division
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear2DBlockPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear3DBlockPattern.java
Labels: Bugfix
