Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2023-06, with the labels that each got.

#2262 Update gradle to 8
  .github/workflows/codeql.yml
  buildSrc/build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_18_2/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19_3/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19_4/build.gradle.kts
  worldedit-core/doctools/build.gradle.kts
Labels: dependencies

#2264 Fix BlockEntity#remove spigot mapping
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
Labels: Bugfix

#2241 feat: improve error when loading biomes
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweAdapter.java
Labels: Feature

#2269 Archive PR artifacts
  .github/workflows/build-pr.yml
Labels: chore

#2271 chore: minor improvements to processing-related code
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Labels: chore

#2270 fix: correctly processSet with blacklist when required
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/MultiRegionExtent.java
Labels: Bugfix

#2266 chore: improve queue documentation and submit history to better queue
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/BukkitQueueHandler.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/QueueHandler.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TaskManager.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/AsyncNotifyQueue.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/FaweForkJoinWorkerThreadFactory.java
Labels: chore

#2267 feat: implement a player-specific queue for clipboard IO tasks
  worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/KeyQueuedExecutorService.java
  worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
Labels: Feature

#2273 Optimize PR builds
  .github/workflows/build-pr.yml
  .github/workflows/codeql.yml
Labels: chore

#2277 Improve exception handling on adapter loading
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
Labels: Bugfix

#2282 Set proper field access and use mappings for entities on spigot
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java
Labels: Bugfix

#2279 Update & Fix TownyFeature support.
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/TownyFeature.java
Labels: Bugfix, Feature

#2246 feat: send one of an error message during edits if otherwise squashed by LimitExtent
  worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweCache.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/exception/FaweException.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#2286 feat: add new tree types to tree tool and brush
  worldedit-bukkit/src/test/java/com/sk89q/worldedit/bukkit/BukkitWorldTest.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
Labels: Feature

#2299 fix: don't "double-up" a setblocks if a region is being set
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
Labels: Bugfix

#2308 chore: Address kotlin String#capitalize() deprecation
  buildSrc/src/main/kotlin/LibsConfig.kt
Labels: chore

#2305 fix: use new array when creating palette
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java
Labels: Bugfix

#2302 fix: always return the changeset from EditSessionBuilder
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
Labels: Bugfix

#2306 fix: add missing BlockType constructor
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java
Labels: Bugfix

#2301 fix: towny max bounds are exclusive
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/TownyFeature.java
Labels: Bugfix

#2300 fix: uncache the chunk SET at a better time in ChunkHolder to prevent "lost" changes
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
Labels: Bugfix

#2314 fix: ensure mask is initialised upon visiting a point in BreadthFirstSearch
  worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/BreadthFirstSearch.java
Labels: Bugfix

#2304 refactor: efficiency improvements to some editsession methods
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Labels: chore

#2311 feat: implement removal of entities if they would be in a block after the edit
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/EntityInBlockRemovingProcessor.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/ProcessorScope.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/entity/ExtentEntityCopy.java
Labels: Feature

#2316 Drop support for minor 1.19 versions
  .github/ISSUE_TEMPLATE/bug_report.yml
  build.gradle.kts
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  settings.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R1/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R1/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R1/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R1/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/nbt/PaperweightLazyCompoundTag.java
  worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_19_3/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R2/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R2/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R2/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R2/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/nbt/PaperweightLazyCompoundTag.java
  worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_20/build.gradle.kts
  worldedit-bukkit/build.gradle.kts
Labels: Breaking change
