Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2024-09, with the labels that each got.

#2900 fix: hollow on large areas fails
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Labels: Bugfix

#2906 Avoid map lookup in `isMovementBlocker` calls
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightBlockMaterial.java
Labels: Feature

#2903 fix(GriefDefender): invalidate mask on claim change
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefDefenderFeature.java
Labels: Bugfix

#2891 Replace usages and overrides of deprecated getSuggestions method
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AdjacentMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AngleMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/BesideMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/ExtremaMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/ROCAngleMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RadiusMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichOffsetMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/SimplexMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/SurfaceAngleMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/AngleColorPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/AverageColorPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BiomePatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BufferedPattern2DParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BufferedPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/ColorPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/DesaturatePatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/Linear2DPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/Linear3DPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/LinearPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/MaskedPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoXPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoYPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoZPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoisePatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/OffsetPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RandomFullClipboardPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RandomOffsetPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RelativePatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/SaturatePatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/SolidRandomOffsetPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/SurfaceRandomOffsetPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/TypeSwapPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/Linear3DTransformParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/LinearTransformParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/OffsetTransformParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/PatternTransformParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/RotateTransformParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/ScaleTransformParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/SpreadTransformParser.java
Labels: chore

#2902 fix: don't process out of bound section while trimming Y sections
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
  worldedit-core/src/test/java/com/fastasyncworldedit/core/queue/IBatchProcessorTest.java
Labels: Bugfix

#2901 fix: allow webinterface schematic format to be detected
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
Labels: Bugfix

#2898 Faster undo operations
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/ChangePopulator.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractDelegateChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/ChangeExchangeCoordinator.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/NullChangeSet.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ChangeSetExecutor.java
Labels: Feature

#2910 fix: account for spigot having private PalettedContainer#get(int)
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java
Labels: Bugfix

#2881 Fix regen on modern versions
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/regen/PaperweightRegen.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
Labels: Bugfix

#2914 fix: compound tags can be nullable when converting state to baseblock
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/world/block/CompoundInput.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
Labels: Bugfix

#2890 Introduce basic support for Vector API
  build.gradle.kts
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/CountFilter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/MaskFilter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/SimdSupport.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedCharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedFilter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Mask.java
Labels: Feature

#2919 Revert history writing using LinBinaryIO
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
Labels: Bugfix

#2858 feat: improve fawe limits (#2773)
  worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweCache.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/EditSessionHolder.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/ProvideBindings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/ABlockMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/DataMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/IdMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/SingleBlockStateMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/SplatterBrushMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BiomeCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/HistoryCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SnapshotUtilCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/BlockDataCyler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/BlockReplacer.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/SinglePickaxe.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/StackTool.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/TreePlanter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/Brush.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/ConfirmHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/PreloadHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/SynchronousSettingExpected.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/package-info.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BiomeMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockCategoryMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockStateMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockTypeMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/ExistingBlockMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/InverseSingleBlockStateMask.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Bugfix, Feature

#2922 Fix tile copying
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/LinearClipboard.java
Labels: Bugfix

#2920 fix: add timeout to reading history from exchanger
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/ChangeExchangeCoordinator.java
Labels: Bugfix

#2913 fix: adjust linked filter to be left-right and do not link to new forked instances
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ChunkFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/Filter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IDelegateFilter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Labels: Bugfix

#2909 fix: apply origin to sponge v3 schematics
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/sponge/SpongeSchematicV3Reader.java
Labels: Bugfix

#2853 fix: some improvements to GET chunk writing
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightStarlightRelighter.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkitWorld.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/IntPair.java
Labels: Bugfix

#2929 Fix NBT stripping and trimming
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/StripNBTExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBlocks.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java
Labels: Bugfix

#2927 Implement vectorization of #existing and inverse masks
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/SimdSupport.java
Labels: Feature
