Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2024-06, with the labels that each got.

#2754 fix: improve how we determine if using FAWE from jenkins
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java
Labels: Bugfix

#2745 feat: schematic share system, add missing Clipboard method for api compat
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/arkitektonika/ArkitektonikaResponse.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/arkitektonika/ArkitektonikaSchematicUploader.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/ClipboardFormatConverter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/ClipboardShareDestinationConverter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/Clipboard.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormats.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/share/BuiltInClipboardShareDestinations.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/share/ClipboardShareDestination.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/share/ClipboardShareDestinations.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/share/ClipboardShareMetadata.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/share/ShareOutputProvider.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/ClipboardTransformBaker.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#2753 fix: correctly trim the max chunk section
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
Labels: Bugfix

#2764 fix: normalize layer when setting ordinal to ThreadUnsafeCharBlocks
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/ThreadUnsafeCharBlocks.java
Labels: Bugfix

#2767 Fix more upstream incompatibilities
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/share/ClipboardShareMetadata.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/factory/Deform.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Mask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Masks.java
  worldedit-core/src/main/java/com/sk89q/worldedit/history/change/BiomeChange3D.java
  worldedit-core/src/main/java/com/sk89q/worldedit/history/change/BlockChange.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/exception/ExceptionConverterHelper.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/event/InteractionDebouncer.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/ExecutionData.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/ExpressionHelper.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/Functions.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/LocalSlot.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/SlotTable.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/invoke/CompilingVisitor.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/invoke/ExecNode.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/invoke/ExpressionHandles.java
  worldedit-core/src/main/java/com/sk89q/worldedit/registry/Keyed.java
  worldedit-core/src/main/java/com/sk89q/worldedit/session/Placement.java
  worldedit-core/src/main/java/com/sk89q/worldedit/session/PlacementType.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/LocatedBlock.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/report/DataReport.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeType.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/entity/EntityType.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/fluid/FluidType.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/gamemode/GameMode.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/ItemMaterial.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/PassthroughItemMaterial.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/SimpleItemMaterial.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/weather/WeatherType.java
Labels: Bugfix, chore

#2752 fix: ensure config-legacy.yml is created before accessed
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Config.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/file/YamlConfiguration.java
Labels: Bugfix

#2786 fix: allow use of quotes to allow spaces to be used as "and"
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/TransformFactory.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/FaweParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/BlockFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/ItemFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/AbstractFactory.java
Labels: Bugfix

#2757 fix: improve biome setting to avoid writing directly to chunk
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java
Labels: Bugfix

#2787 fix: correclty create Minecraft Structure format schematics
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/schematic/MinecraftStructure.java
Labels: Bugfix

#2771 fix: recover from trimmed chunk
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java
Labels: Bugfix

#2788 fix: always init ChunkFilterBlock to the chunk
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/PolyhedralRegion.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/Triangle.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/EllipsoidRegion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Labels: Bugfix

#2782 fix: take confirm-large from default limit for unlimited, add option to override
  worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/WorldEditCommands.java
Labels: Bugfix

#2791 fix: create new biome paletted container when writing
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks_Copy.java
Labels: Bugfix

#2789 fix: correctly process chunks when using worldguard region blacklists
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/WorldGuardFeature.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/RegionIntersection.java
Labels: Bugfix

#2797 fix: correct y index addition in biome history
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
Labels: Bugfix

#2772 fix: extract new config option for deleting disk history on logout
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Config.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
Labels: Bugfix

#2802 fix: only write copied value if non null
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Config.java
Labels: Bugfix

#2777 Add a BiomeCategories API (#2338)
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R3/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R3/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R1/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R1/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R3/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R3/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R3/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R4/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R4/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R4/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IDelegateBukkitImplAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/BukkitImplAdapter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReader.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/wna/WorldNativeAccess.java
  worldedit-core/src/main/java/com/sk89q/worldedit/registry/Category.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeCategory.java
Labels: Feature

#2804 feat: implement graceful world bounds check where appropriate
  worldedit-core/src/main/java/com/fastasyncworldedit/core/exception/OutsideWorldBoundsException.java
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/exception/WorldEditExceptionConverter.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#2783 feat: add option to prevent parsing legacy blocks to the FaweLimit
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/scroll/Scroll.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/ConsumeBindings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GeneralCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/FactoryConverter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/BlocksMaskParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/scripting/CraftScriptContext.java
Labels: Feature

#2808 feat: implement 1.21
  build.gradle.kts
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/StaticRefraction.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/nbt/PaperweightLazyCompoundTag.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/regen/PaperweightRegen.java
  worldedit-bukkit/build.gradle.kts
Labels: Feature
