Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2024-05, with the labels that each got.

#2642 feat: introduce migrating config nodes to new locations
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Config.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
Labels: Feature

#2722 fix: add missing blocktypes and some minor cleanup
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
Labels: Bugfix

#2723 feat: only unstuck a player if configured to do so
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
Labels: Feature

#2743 Fix compatibility with WorldGuard
  worldedit-bukkit/adapters/adapter-1_20_5/build.gradle.kts
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/AbstractFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ArrayFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/FilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/SingleFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/DelegateBlockVector3.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/MutableBlockVector3.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/MutableVector3.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/OffsetBlockVector3.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/Vector3Impl.java
  worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector2.java
  worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3.java
  worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3Imp.java
  worldedit-core/src/main/java/com/sk89q/worldedit/math/Vector2.java
  worldedit-core/src/main/java/com/sk89q/worldedit/math/Vector3.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/Location.java
Labels: chore

#2751 fix: ClassCastException on spigot
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java
Labels: Bugfix
