Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2024-08, with the labels that each got.

#2863 fix: do not StackOverflow when getting a section in FULL after awkward trim
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java
Labels: Bugfix

#2877 Support 1.21.1
  build.gradle.kts
  buildSrc/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java
Labels: Major feature

#2824 chore: warn when both history db and delete disk on logout are enabled
  worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
Labels: chore

#2899 Fix: Copy-Paste-Brush with falsy mask
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/ResizableClipboardBuilder.java
Labels: Bugfix
