Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2024-07, with the labels that each got.

#2803 fix: override min/max pos methods from SimpleClipboard
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/ReadOnlyClipboard.java
Labels: Bugfix

#2816 fix: switch to 3d where 2d biomes still remain in a couple of places
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/FaweRegionExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/TransformExtent.java
Labels: Bugfix

#2807 fix: clone polyhedral region last triangle too if present
  worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/PolyhedralRegion.java
Labels: Bugfix

#2827 Add worldedit.tool.none to fawe.permpack.basic
  worldedit-bukkit/src/main/resources/plugin.yml
Labels: Enhancement

#2836 Compile with target java 21, remove unsupported MC versions
  .github/ISSUE_TEMPLATE/bug_report.yml
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  settings.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19_4/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R3/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R3/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R3/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R3/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/nbt/PaperweightLazyCompoundTag.java
  worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/regen/PaperweightRegen.java
  worldedit-bukkit/adapters/adapter-1_20/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R1/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R1/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R1/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R1/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/nbt/PaperweightLazyCompoundTag.java
  worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/regen/PaperweightRegen.java
Labels: chore

#2839 Fix parseFromInput Method for Masks and Patterns When Called via API
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java
Labels: Bugfix

#2842 fix: use new index calculations for BlockVectorSet remove
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java
Labels: Bugfix

#2817 fix: improve SchemGen, allow null mask (reordered command args)
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/PopulateSchem.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/SchemGen.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java
Labels: Bugfix

#2838 fix: improve schematic format selection
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormat.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormats.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Bugfix

#2852 chore: deprecate FaweApi#load for clipboards as it does not allow closing
  worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweAPI.java
Labels: chore

#2850 feat: add litematica error when failing to load schematic
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV2.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#2773 feat: improve fawe limits
  worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweCache.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/EditSessionHolder.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/ProvideBindings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/ABlockMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/DataMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/IdMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/SingleBlockStateMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/SplatterBrushMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/ConcurrentFaweLimit.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/ProcessorFaweLimit.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BiomeCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/HistoryCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SnapshotUtilCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/AreaPickaxe.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/BlockDataCyler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/BlockReplacer.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/BrushTool.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/FloatingTreeRemover.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/FloodFillTool.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/LongRangeBuildTool.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/RecursivePickaxe.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/SinglePickaxe.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/StackTool.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/TreePlanter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/Brush.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/ConfirmHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/PreloadHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/SynchronousSettingExpected.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/package-info.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BiomeMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockCategoryMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockStateMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockTypeMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/ExistingBlockMask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/InverseSingleBlockStateMask.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#2844 fix: improve FAWE stream history
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/CopyPastaBrush.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractDelegateChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/history/changeset/ChangeSet.java
Labels: Bugfix

#2857 fix: correctly resolve file if extension is given
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormats.java
Labels: Bugfix
