Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2024-11, with the labels that each got.

#2973 Allow stacking by block units with //stack (#1539)
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#2972 Fix direction changes for //undo
  worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
Labels: Bugfix

#2967 Deduplicate adapter fields into superclass
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java
Labels: chore

#2962 Make property changes more robust
  worldedit-core/src/main/java/com/fastasyncworldedit/core/registry/state/PropertyKey.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java
Labels: Bugfix

#2867 feat: alter clipboard thread to move all clipboard loading from main thread
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/UUIDKeyQueuedThreadFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlayerActor.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#2974 1.21.3
  .github/ISSUE_TEMPLATE/bug_report.yml
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21_3/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_3/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_3/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_3/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_3/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_3/StaticRefraction.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/regen/PaperweightRegen.java
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/test/java/com/sk89q/wepif/TestOfflinePermissible.java
Labels: Feature

#2988 Un-break for versions <1.21.3
  gradle/libs.versions.toml
  worldedit-bukkit/src/test/java/com/sk89q/wepif/TestOfflinePermissible.java
Labels: Bugfix

#2976 fix: correctly check for properties in thaw/snow
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/block/SnowSimulator.java
  worldedit-core/src/main/java/com/sk89q/worldedit/registry/state/AbstractProperty.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java
Labels: Bugfix

#2999 Synchronize bundled data with WE
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/Constants.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/BundledItemData.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/BundledRegistries.java
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.115.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.116.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.117.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.119.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.121.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.1213.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.115.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.116.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.117.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.119.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.121.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.1213.json
Labels: chore

#3005 Send forget packet to avoid invisible chunk sections
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightPlatformAdapter.java
Labels: Bugfix

#3004 Move some classes to their expected location
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-bukkit/build.gradle.kts
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskUnion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskUnion2D.java
Labels: Bugfix
