Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2024-03, with the labels that each got.

#2591 fix rollback database query
  worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java
Labels: Bugfix

#2594 Decrease lock contention in SingleThreadQueueExtent
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/QueueHandler.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
Labels: Enhancement

#2603 Maintain insertion order for RandomPattern sub-patterns
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/RandomCollection.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/RandomPattern.java
Labels: Bugfix

#2614 fix: do not forcefully direct to x,y,z methods in AbstractDelegateExtent
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
Labels: Bugfix

#2617 fix: set and clone Expression Environment after Expression cloning
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/Expression.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/ExpressionEnvironment.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java
  worldedit-core/src/test/java/com/sk89q/worldedit/internal/expression/BaseExpressionTest.java
Labels: Bugfix

#2620 fix: correctly (de)serialise ItemType
  worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/GsonUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/ItemTypeAdapter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemType.java
Labels: Bugfix

#2611 Make sure to process all chunks in PQE even if PARALLEL_THREADS = 1
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
Labels: Bugfix

#2613 Allow factory suggestions to have parser context
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/RichParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/FactoryConverter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/AbstractFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/InputParser.java
Labels: Enhancement

#2623 chore: deprecate transform extent for removal
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/TransformExtent.java
Labels: chore

#2624 Allow repeated keys in RandomCollection
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/transform/RandomTransform.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/FastRandomCollection.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/RandomCollection.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/SimpleRandomCollection.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/RandomPattern.java
Labels: Feature

#2615 refactor: apply final/abstract to various fawe extent classes
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/BlockTranslateExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/DisallowedBlocksExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ExtentHeightCacher.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/HeightBoundExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/HistoryExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/MemoryCheckingExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/MultiRegionExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/NullExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/PassthroughExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/PositionTransformExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ProcessedWEExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ResettableExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/SingleRegionExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/SlowExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/SourceMaskExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/StripNBTExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/SupplyingExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/TemporalExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/TransformExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java
Labels: chore

#2627 Drop support for 1.17.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  build.gradle.kts
  settings.gradle.kts
  worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/nbt/PaperweightLazyCompoundTag.java
  worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java
  worldedit-bukkit/build.gradle.kts
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitServerInterface.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
Labels: Breaking changes

#2625 fix: do not error when attempting to parse "|" as a pattern
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
Labels: Bugfix

#2628 Reword tree type message
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
Labels: chore

#2630 Implement linear patterns using RandomPattern + SimpleRandom
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/Linear2DPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/Linear3DPatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear2DBlockPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear3DBlockPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/random/Linear2DRandom.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/random/Linear3DRandom.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/random/SimpleRandom.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/SimpleRandomCollection.java
Labels: Feature

#2632 fix: better image reading errors
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/HeightBrush.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
Labels: Bugfix

#2629 Update paperweight 1.20.4 - isOpaque does not exist (anymore)
  worldedit-bukkit/adapters/adapter-1_20_4/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightBlockMaterial.java
Labels: Bugfix

#2621 feat: save region selector to session store
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/gson/ItemTypeAdapter.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/gson/RegionSelectorAdapter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/selector/RegionSelectorType.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/GsonUtil.java
Labels: Feature

#2637 fix: imgur image resolution, image input stream reading
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
Labels: Bugfix

#2645 Fix queryRel returning data value for block at absolute coordinates
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java
Labels: Bugfix

#2626 Fix Linear pattern index incrementing above array length
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/LinearBlockPattern.java
Labels: Bugfix

#2649 Use correct find class in ExtentTraverser
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ExtentTraverser.java
Labels: Bugfix

#2651 Simplify processor ordering
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/MultiBatchProcessor.java
Labels: chore

#2633 Make usage of stateful patterns thread-safe
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/ExpressionPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear2DBlockPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear3DBlockPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/LinearBlockPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/MaskedPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/NoXPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/NoYPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/NoZPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/OffsetPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomOffsetPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RelativePattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SolidRandomOffsetPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/buffer/ForgetfulExtentBuffer.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/ExtentBufferedCompositePattern.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/Pattern.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/RandomPattern.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/StateApplyingPattern.java
Labels: Bugfix

#2631 fix: introduce approx size to patterns and use in ScatterBrush
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ScatterBrush.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ShatterBrush.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/OffsetPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomOffsetPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/math/MutableBlockVector3.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/BlockVector3Set.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/Pattern.java
Labels: Bugfix
