Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2025-08, with the labels that each got.

#3259 fix: correct `/fawe version` version
  worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweVersion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/WorldEditCommands.java
Labels: Bugfix

#3269 feat: add BlockVector3 radius square to Ellipsoid to reduce rounding
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/EllipsoidRegion.java
Labels: Feature

#3277 Address more getSuggestions deprecations
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/RichParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BiomePatternParser.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/RandomTransformParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/util/SuggestionHelper.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/BlocksMaskParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/NegateMaskParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/OffsetMaskParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomPatternParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomStatePatternParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/SingleBlockPatternParser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/TypeOrStateApplyingPatternParser.java
Labels: chore

#3276 Use RandomPattern instead of RandomStatePattern
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomStatePatternParser.java
Labels: Feature

#3270 Update native Minecraft dependencies
  buildSrc/src/main/kotlin/CommonConfig.kt
  gradle/libs.versions.toml
Labels: Renovate

#3285 fix: 1.21.4 entityManager obf is O not N
  worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightPlatformAdapter.java
Labels: Bugfix

#3297 chore/fix: use mirror repository for paper dev-bundles
  buildSrc/src/main/kotlin/CommonConfig.kt
  worldedit-bukkit/adapters/adapter-1_21_6/build.gradle.kts
Labels: Bugfix, chore

#3289 fix: schematic format detection
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormats.java
  worldedit-core/src/test/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormatsTest.java
  worldedit-core/src/test/resources/fastasyncworldedit/schematics/1x1.png
  worldedit-core/src/test/resources/fastasyncworldedit/schematics/custom_format.xyz
  worldedit-core/src/test/resources/fastasyncworldedit/schematics/mcedit.mce
  worldedit-core/src/test/resources/fastasyncworldedit/schematics/minecraft_structure.nbt
  worldedit-core/src/test/resources/fastasyncworldedit/schematics/sponge1.schem
  worldedit-core/src/test/resources/fastasyncworldedit/schematics/sponge2.schem
  worldedit-core/src/test/resources/fastasyncworldedit/schematics/sponge3.schem
Labels: Bugfix

#3298 hotfix: revert shadow plugin upgrade
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/LibsConfig.kt
  buildSrc/src/main/kotlin/PlatformConfig.kt
Labels: Bugfix
