Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2025-07, with the labels that each got.

#3243 chore: update publishing
  .github/workflows/build.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/LibsConfig.kt
  buildSrc/src/main/kotlin/PlatformConfig.kt
Labels: chore, skip-changelog

#3244 fix: pasting of colored signs
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_6/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_6/PaperweightAdapter.java
Labels: Bugfix

#3249 fix: we should just always clone the region in ApplyTask
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ApplyTask.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/ConvexPolyhedralRegion.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/polyhedron/Triangle.java
Labels: Bugfix

#3247 feat: lazily resolve NBT on items
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_6/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_6/PaperweightFaweAdapter.java
Labels: Feature
