Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2025-04, with the labels that each got.

#3137 chore: cherry-pick appropriate changes from upstream
  .gitignore
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R4/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_4/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockRegistry.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/MorphBrush.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/ChangeSetExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/reorder/MultiStageReorder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/factory/BiomeFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/Constants.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/CommandUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/cui/ServerCUIHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/factory/FixedHeightCuboidRegionFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/factory/FixedHeightCylinderRegionFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/SideEffectSet.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BaseBlock.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockStateHolder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/entity/EntityTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/BundledRegistries.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/snapshot/SnapshotRestore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/McRegionChunkStore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/McRegionReader.java
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.1212.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.1212.json
  worldedit-core/src/main/resources/lang/strings.json
  worldedit-core/src/test/java/com/sk89q/worldedit/util/SideEffectSetTest.java
  worldedit-core/src/test/resources/junit-platform.properties
Labels: chore

#3158 Revert "chore: cherry-pick appropriate changes from upstream"
  .gitignore
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R4/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_4/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockRegistry.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/MorphBrush.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/ChangeSetExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/reorder/MultiStageReorder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/factory/BiomeFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/Constants.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/CommandUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/cui/ServerCUIHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/factory/FixedHeightCuboidRegionFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/factory/FixedHeightCylinderRegionFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/SideEffectSet.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BaseBlock.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockStateHolder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/entity/EntityTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/BundledRegistries.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/snapshot/SnapshotRestore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/McRegionChunkStore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/McRegionReader.java
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.1212.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.1212.json
  worldedit-core/src/main/resources/lang/strings.json
  worldedit-core/src/test/java/com/sk89q/worldedit/util/SideEffectSetTest.java
  worldedit-core/src/test/resources/junit-platform.properties
Labels: chore

#3159 Upstream Updates
  .gitignore
  buildSrc/src/main/kotlin/CommonJavaConfig.kt
  buildSrc/src/main/kotlin/PlatformConfig.kt
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R4/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_4/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockRegistry.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
  worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
  worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
  worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/MorphBrush.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformManager.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/ChangeSetExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java
  worldedit-core/src/main/java/com/sk89q/worldedit/extent/reorder/MultiStageReorder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/factory/BiomeFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/Constants.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/CommandUtil.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/cui/ServerCUIHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/factory/FixedHeightCuboidRegionFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/factory/FixedHeightCylinderRegionFactory.java
  worldedit-core/src/main/java/com/sk89q/worldedit/util/SideEffectSet.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BaseBlock.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockStateHolder.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/entity/EntityTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemCategories.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemTypes.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/BundledRegistries.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/snapshot/SnapshotRestore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/McRegionChunkStore.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/McRegionReader.java
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/blocks.1212.json
  worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/items.1212.json
  worldedit-core/src/main/resources/lang/strings.json
  worldedit-core/src/test/java/com/sk89q/worldedit/util/SideEffectSetTest.java
  worldedit-core/src/test/resources/junit-platform.properties
Labels: chore

#3161 fix: saving of blocks with tile entity data in FAST_V3
  buildSrc/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21_4/build.gradle.kts
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicWriterV3.java
Labels: Bugfix

#3168 feat: add upstream's trim command (EngineHub/WorldEdit#2278)
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
  worldedit-core/src/main/resources/lang/strings.json
Labels: Feature

#3170 chore: improve performance of upstream's trim command
  worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
Labels: chore

#3172 Update for 1.21.5
  build.gradle.kts
  settings.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21_5/build.gradle.kts
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightDataConverters.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightFakePlayer.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightServerLevelDelegateProxy.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/StaticRefraction.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightBlockMaterial.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightFaweMutableBlockPlaceContext.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightFaweWorldNativeAccess.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightGetBlocks.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightGetBlocks_Copy.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightLevelProxy.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightMapChunkUtil.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightPlacementStateProcessor.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightPlatformAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightPostProcessor.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightStarlightRelighter.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightStarlightRelighterFactory.java
  worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/regen/PaperweightRegen.java
  worldedit-core/src/main/java/com/sk89q/worldedit/internal/Constants.java
Labels: Feature

#3185 fix: don't return null when slow applyBlock method is called by CoreProtect
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/PlacementStateProcessor.java
Labels: Bugfix

#3182 fix: attempt to retrieve online from offline player for perm attachments
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/BukkitPermissionAttachmentManager.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java
Labels: Bugfix
