Repository IntellectualSites/FastAsyncWorldEdit, pull requests merged in 2025-02, with the labels that each got.

#3091 chore: make update-checker more configurable and link other download pages
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditListener.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java
  worldedit-core/src/main/resources/lang/strings.json
  worldedit-core/src/test/java/com/fastasyncworldedit/core/util/UpdateNotificationTest.java
Labels: chore

#3057 feat: Using Block Registry to Replace Iterating Over the Material Enum
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java
  worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IDelegateBukkitImplAdapter.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockRegistry.java
  worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/BukkitImplAdapter.java
  worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/BlockRegistry.java
Labels: Feature

#3106 Add 1.21.4 for bug reports
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore, skip-changelog

#3101 Fix mutability issue leading to wrong behavior in //ascend and //descend
  worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlayerActor.java
Labels: Bugfix

#3072 Optimize AngleMask
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/ABlockMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AngleMask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/CachedMask.java
Labels: chore

#3109 Restore Spigot compatibility
  worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java
  worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java
Labels: Bugfix

#3098 Make #clipboard in height brush work again
  worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
Labels: Bugfix

#3103 Support single y level processing using Vector API
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorFacade.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedCharFilterBlock.java
Labels: chore

#3115 fix: entity fixup in sponge v3 schematics
  worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java
Labels: Bugfix

#3114 feat: improve output with better-entity usage
  worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ExtentTraverser.java
  worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java
Labels: Feature

#3102 Locality-aware chunk distribution
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ApplyTask.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
  worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/QueueHandler.java
  worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Labels: Enhancement
